[package]
name = "discord_smp_link"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.63", features = ["backtrace"] }
askama = "0.11.1"
diesel = { version = "2.0.0", default-features = false, features = [
	"mysql",
	"chrono",
	"r2d2",
] }
futures = "0.3.24"
hyper = "0.14.20"
hyper-rustls = { version = "0.23.0", features = ["rustls-native-certs"] }
poise = { git = "https://github.com/kangalioo/poise", branch = "develop" }
oauth2 = "4.2.3"
rouille = "3.5.0"
serde = "1.0.144"
tokio = { version = "1.20.1", features = ["macros", "rt-multi-thread"] }
dotenvy = "0.15.3"
console = "0.15.1"
chrono = "0.4.22"
uuid = { version = "1.1.2", features = ["v4"] }
serde_json = "1.0.85"
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
tracing-appender = "0.2.2"
fluent = "0.16.0"
intl-memoizer = "0.5.1"
fluent-syntax = "0.11.0"
unic-langid = { version = "0.9.0", features = ["macros"] }
diesel_migrations = { version = "2.0.0", features = ["mysql"] }
thiserror = "1.0.33"
