version: '3.9'

networks:
    database:


services:
    database:
        image: mariadb
        restart: unless-stopped
        environment:
            MARIADB_DATABASE: server
            MARIADB_USER: server
            MARIADB_PASSWORD: server
            MARIADB_RANDOM_ROOT_PASSWORD: true
        networks:
            - database
