version: '3.7'

services:
    client:
        build: ghcr.io/mrnossiom/discord-smp-link:latest
        volumes:
            - .env.docker:/discord_smp_link/.env
        depends_on:
            database: 
                condition: service_healthy
        network_mode: "host"

    database:
        image: mariadb
        environment:
            MARIADB_DATABASE: server
            MARIADB_USER: server
            MARIADB_PASSWORD: server
            MARIADB_RANDOM_ROOT_PASSWORD: true
        ports:
            - 3306:3306
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u $$MARIADB_USER -p=$$MARIADB_PASSWORD
            timeout: 5s
            retries: 10

    logs_sink:
        image: timberio/vector:0.24.X-distroless-static
        ports:
            - 8686:8686
        volumes:
            - ~/vector.toml:/etc/vector/vector.toml
