version: '3.9'

services:
    database:
        image: mariadb
        environment:
            MARIADB_DATABASE: server
            MARIADB_USER: server
            MARIADB_PASSWORD: server
            MARIADB_RANDOM_ROOT_PASSWORD: true
        ports:
            - 3306:3306