version: '3.7'

services:
    db:
        image: postgres
        environment:
            POSTGRES_USER: server
            POSTGRES_PASSWORD: server
        ports:
            - 5432:5432
    client:
        build: .
        volumes:
            - .env.docker:/tmp/discord_smp_link/.env
            - ./logs/:/tmp/discord_smp_link/logs
        depends_on: [database]
        network_mode: "host"