version: '3.7'

networks:
    caddy:
    database:


services:
    client:
        # TODO: change the tag to latest
        image: ghcr.io/mrnossiom/discord-smp-link:dev
        volumes:
            - .env.docker:/discord_smp_link/.env
        depends_on:
            database:
                condition: service_healthy
        networks: [ database, caddy ]

    # MySQL database
    database:
        image: mariadb
        environment:
            MARIADB_DATABASE: server
            MARIADB_USER: server
            MARIADB_PASSWORD: server
            MARIADB_RANDOM_ROOT_PASSWORD: true
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u $$MARIADB_USER -p$$MARIADB_PASSWORD
            timeout: 2s
            retries: 20
        networks: [ database ]

    # Reverse proxy for the Rocket server
    caddy:
        image: caddy:latest
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - ./.caddy/site:/srv
            - ./.caddy/caddy_data:/data
            - ./.caddy/caddy_config:/config
        networks: [ caddy ]

    # Gets logs and send them to the LogTail bucket
    logs_sink:
        image: timberio/vector:0.24.X-distroless-static
        expose: [ 8686 ]
        network_mode: bridge
        env_file:
            - .env.docker
        volumes:
            - ./vector.toml:/etc/vector/vector.toml
            - ./transform.vrl:/etc/vector/transform.vrl
            - /var/run/docker.sock:/var/run/docker.sock
