[build]
rustflags = ["--cfg", "tokio_unstable", "-Ctarget-cpu=native"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["--cfg", "tokio_unstable"]

[target.x86_64-apple-darwin]
rustflags = ["--cfg", "tokio_unstable"]

[target.aarch64-apple-darwin]
rustflags = ["--cfg", "tokio_unstable"]

[target.x86_64-pc-windows-msvc]
rustflags = ["--cfg", "tokio_unstable"]

[profile.dev]
debug = 1
